version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gin_backend
    ports:
      - "8001:8001"
    env_file: 
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - trainify_network

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: Amirmusic1
      MYSQL_DATABASE: trainify
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - trainify_network

volumes:
  db_data:

networks:
  trainify_network:
